// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/indexer/payload/event.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// enum to specify that the IndexerTendermintEvent is a block event.
type IndexerTendermintEvent_BlockEvent int32

const (
	// BLOCK_EVENT indicates that the event was generated during processing of the block rather
	// than any specific transaction e.g. during FinalizeBlock.
	IndexerTendermintEvent_BLOCK_EVENT IndexerTendermintEvent_BlockEvent = 0
)

var IndexerTendermintEvent_BlockEvent_name = map[int32]string{
	0: "BLOCK_EVENT",
}

var IndexerTendermintEvent_BlockEvent_value = map[string]int32{
	"BLOCK_EVENT": 0,
}

func (x IndexerTendermintEvent_BlockEvent) String() string {
	return proto.EnumName(IndexerTendermintEvent_BlockEvent_name, int32(x))
}

func (IndexerTendermintEvent_BlockEvent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a753710efdd2ea21, []int{0, 0}
}

// IndexerTendermintEvent contains the base64 encoded event proto emitted from the V4 application
// as well as additional metadata to determine the ordering of the event within the block and the
// subtype of the event.
type IndexerTendermintEvent struct {
	Subtype string `protobuf:"bytes,1,opt,name=subtype,proto3" json:"subtype,omitempty"`
	// Base64 encoded proto from the Tendermint event.
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// ordering_within_block is either the transaction index or a boolean indicating the event was
	// generated during processing the block rather than any specific transaction e.g. during
	// FinalizeBlock.
	//
	// Types that are valid to be assigned to OrderingWithinBlock:
	//
	//	*IndexerTendermintEvent_TransactionIndex
	//	*IndexerTendermintEvent_IsBlockEvent
	OrderingWithinBlock isIndexerTendermintEvent_OrderingWithinBlock `protobuf_oneof:"ordering_within_block"`
	// Index of the event within the list of events that happened either during a transaction or
	// during processing of a block.
	EventIndex uint32 `protobuf:"varint,5,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
}

func (m *IndexerTendermintEvent) Reset()         { *m = IndexerTendermintEvent{} }
func (m *IndexerTendermintEvent) String() string { return proto.CompactTextString(m) }
func (*IndexerTendermintEvent) ProtoMessage()    {}
func (*IndexerTendermintEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a753710efdd2ea21, []int{0}
}
func (m *IndexerTendermintEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndexerTendermintEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndexerTendermintEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndexerTendermintEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexerTendermintEvent.Merge(m, src)
}
func (m *IndexerTendermintEvent) XXX_Size() int {
	return m.Size()
}
func (m *IndexerTendermintEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexerTendermintEvent.DiscardUnknown(m)
}

var xxx_messageInfo_IndexerTendermintEvent proto.InternalMessageInfo

type isIndexerTendermintEvent_OrderingWithinBlock interface {
	isIndexerTendermintEvent_OrderingWithinBlock()
	MarshalTo([]byte) (int, error)
	Size() int
}

type IndexerTendermintEvent_TransactionIndex struct {
	TransactionIndex uint32 `protobuf:"varint,3,opt,name=transaction_index,json=transactionIndex,proto3,oneof" json:"transaction_index,omitempty"`
}
type IndexerTendermintEvent_IsBlockEvent struct {
	IsBlockEvent IndexerTendermintEvent_BlockEvent `protobuf:"varint,4,opt,name=is_block_event,json=isBlockEvent,proto3,enum=dydxprotocol.indexer.payload.IndexerTendermintEvent_BlockEvent,oneof" json:"is_block_event,omitempty"`
}

func (*IndexerTendermintEvent_TransactionIndex) isIndexerTendermintEvent_OrderingWithinBlock() {}
func (*IndexerTendermintEvent_IsBlockEvent) isIndexerTendermintEvent_OrderingWithinBlock()     {}

func (m *IndexerTendermintEvent) GetOrderingWithinBlock() isIndexerTendermintEvent_OrderingWithinBlock {
	if m != nil {
		return m.OrderingWithinBlock
	}
	return nil
}

func (m *IndexerTendermintEvent) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

func (m *IndexerTendermintEvent) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *IndexerTendermintEvent) GetTransactionIndex() uint32 {
	if x, ok := m.GetOrderingWithinBlock().(*IndexerTendermintEvent_TransactionIndex); ok {
		return x.TransactionIndex
	}
	return 0
}

func (m *IndexerTendermintEvent) GetIsBlockEvent() IndexerTendermintEvent_BlockEvent {
	if x, ok := m.GetOrderingWithinBlock().(*IndexerTendermintEvent_IsBlockEvent); ok {
		return x.IsBlockEvent
	}
	return IndexerTendermintEvent_BLOCK_EVENT
}

func (m *IndexerTendermintEvent) GetEventIndex() uint32 {
	if m != nil {
		return m.EventIndex
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IndexerTendermintEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IndexerTendermintEvent_TransactionIndex)(nil),
		(*IndexerTendermintEvent_IsBlockEvent)(nil),
	}
}

// IndexerTendermintBlock contains all the events for the block along with metadata for the block
// height, timestamp of the block and a list of all the hashes of the transactions within the
// block. The transaction hashes follow the ordering of the transactions as they appear within
// the block.
type IndexerTendermintBlock struct {
	Height   uint32                    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Time     time.Time                 `protobuf:"bytes,2,opt,name=time,proto3,stdtime" json:"time"`
	Events   []*IndexerTendermintEvent `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	TxHashes []string                  `protobuf:"bytes,4,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
}

func (m *IndexerTendermintBlock) Reset()         { *m = IndexerTendermintBlock{} }
func (m *IndexerTendermintBlock) String() string { return proto.CompactTextString(m) }
func (*IndexerTendermintBlock) ProtoMessage()    {}
func (*IndexerTendermintBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_a753710efdd2ea21, []int{1}
}
func (m *IndexerTendermintBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndexerTendermintBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndexerTendermintBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndexerTendermintBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexerTendermintBlock.Merge(m, src)
}
func (m *IndexerTendermintBlock) XXX_Size() int {
	return m.Size()
}
func (m *IndexerTendermintBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexerTendermintBlock.DiscardUnknown(m)
}

var xxx_messageInfo_IndexerTendermintBlock proto.InternalMessageInfo

func (m *IndexerTendermintBlock) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *IndexerTendermintBlock) GetTime() time.Time {
	if m != nil {
		return m.Time
	}
	return time.Time{}
}

func (m *IndexerTendermintBlock) GetEvents() []*IndexerTendermintEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *IndexerTendermintBlock) GetTxHashes() []string {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func init() {
	proto.RegisterEnum("dydxprotocol.indexer.payload.IndexerTendermintEvent_BlockEvent", IndexerTendermintEvent_BlockEvent_name, IndexerTendermintEvent_BlockEvent_value)
	proto.RegisterType((*IndexerTendermintEvent)(nil), "dydxprotocol.indexer.payload.IndexerTendermintEvent")
	proto.RegisterType((*IndexerTendermintBlock)(nil), "dydxprotocol.indexer.payload.IndexerTendermintBlock")
}

func init() {
	proto.RegisterFile("dydxprotocol/indexer/payload/event.proto", fileDescriptor_a753710efdd2ea21)
}

var fileDescriptor_a753710efdd2ea21 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0xf5, 0x5e, 0x42, 0xb8, 0x4c, 0xb8, 0xe3, 0x58, 0xc1, 0x61, 0x05, 0x70, 0xac, 0x54, 0x6e,
	0x6e, 0x2d, 0x05, 0x0a, 0x0a, 0x24, 0x24, 0xa3, 0x48, 0x41, 0x9c, 0x40, 0xb2, 0x22, 0x0a, 0x1a,
	0xcb, 0x1f, 0x8b, 0xbd, 0xba, 0xd8, 0x1b, 0x79, 0x37, 0xe0, 0xfc, 0x8b, 0xfb, 0x37, 0xfc, 0x85,
	0x2b, 0xaf, 0x41, 0xa2, 0x02, 0x94, 0xfc, 0x11, 0xe4, 0xb1, 0x23, 0x52, 0x44, 0x14, 0x54, 0x9e,
	0x99, 0x7d, 0xfb, 0xf6, 0xcd, 0x7b, 0x06, 0x27, 0x59, 0x27, 0xd5, 0xb2, 0x94, 0x5a, 0xc6, 0x72,
	0xe1, 0x8a, 0x22, 0xe1, 0x15, 0x2f, 0xdd, 0x65, 0xb8, 0x5e, 0xc8, 0x30, 0x71, 0xf9, 0x17, 0x5e,
	0x68, 0x86, 0xc7, 0xf4, 0xe9, 0x3e, 0x92, 0xb5, 0x48, 0xd6, 0x22, 0x87, 0xa3, 0x54, 0xca, 0x74,
	0xc1, 0x5d, 0x04, 0x44, 0xab, 0xcf, 0xae, 0x16, 0x39, 0x57, 0x3a, 0xcc, 0x97, 0xcd, 0xf5, 0xe1,
	0xc3, 0x54, 0xa6, 0x12, 0x4b, 0xb7, 0xae, 0x9a, 0xe9, 0xf8, 0xdb, 0x11, 0x9c, 0xbf, 0x6d, 0xa8,
	0xe6, 0xbc, 0x48, 0x78, 0x99, 0x8b, 0x42, 0x4f, 0xeb, 0x57, 0xa9, 0x09, 0x77, 0xd5, 0x2a, 0xd2,
	0xeb, 0x25, 0x37, 0x89, 0x4d, 0x9c, 0xbe, 0xbf, 0x6b, 0x29, 0x85, 0x6e, 0x12, 0xea, 0xd0, 0x3c,
	0xc2, 0x31, 0xd6, 0xf4, 0x02, 0x1e, 0xe8, 0x32, 0x2c, 0x54, 0x18, 0x6b, 0x21, 0x8b, 0x00, 0xe5,
	0x99, 0x1d, 0x9b, 0x38, 0x27, 0x33, 0xc3, 0x3f, 0xdb, 0x3b, 0xc2, 0xd7, 0x68, 0x0a, 0xa7, 0x42,
	0x05, 0xd1, 0x42, 0xc6, 0x57, 0x01, 0x2e, 0x69, 0x76, 0x6d, 0xe2, 0x9c, 0x4e, 0x5e, 0xb3, 0x7f,
	0x6d, 0xc9, 0x0e, 0x4b, 0x65, 0x5e, 0xcd, 0x83, 0xe5, 0xcc, 0xf0, 0xef, 0x09, 0xf5, 0xb7, 0xa7,
	0x23, 0x18, 0x20, 0x7f, 0xab, 0xe8, 0x4e, 0xad, 0xc8, 0x07, 0x1c, 0x21, 0xd9, 0xf8, 0x19, 0xc0,
	0x1e, 0xfc, 0x3e, 0x0c, 0xbc, 0xcb, 0x0f, 0x6f, 0xde, 0x05, 0xd3, 0x8f, 0xd3, 0xf7, 0xf3, 0x33,
	0xc3, 0x7b, 0x0c, 0x8f, 0x64, 0x99, 0xf0, 0x52, 0x14, 0x69, 0xf0, 0x55, 0xe8, 0x4c, 0x14, 0x8d,
	0xea, 0xf1, 0x77, 0x72, 0xc0, 0x39, 0x64, 0xa2, 0xe7, 0xd0, 0xcb, 0xb8, 0x48, 0x33, 0x8d, 0xc6,
	0x9d, 0xf8, 0x6d, 0x47, 0x5f, 0x42, 0xb7, 0x4e, 0x05, 0x7d, 0x1b, 0x4c, 0x86, 0xac, 0x89, 0x8c,
	0xed, 0x22, 0x63, 0xf3, 0x5d, 0x64, 0xde, 0xf1, 0xcd, 0xcf, 0x91, 0x71, 0xfd, 0x6b, 0x44, 0x7c,
	0xbc, 0x41, 0x2f, 0xa1, 0x87, 0x92, 0x95, 0xd9, 0xb1, 0x3b, 0xce, 0x60, 0xf2, 0xe2, 0x7f, 0x6c,
	0xf2, 0x5b, 0x0e, 0xfa, 0x04, 0xfa, 0xba, 0x0a, 0xb2, 0x50, 0x65, 0x5c, 0x99, 0x5d, 0xbb, 0xe3,
	0xf4, 0xfd, 0x63, 0x5d, 0xcd, 0xb0, 0xf7, 0x5e, 0xdd, 0x6c, 0x2c, 0x72, 0xbb, 0xb1, 0xc8, 0xef,
	0x8d, 0x45, 0xae, 0xb7, 0x96, 0x71, 0xbb, 0xb5, 0x8c, 0x1f, 0x5b, 0xcb, 0xf8, 0x34, 0x4e, 0x85,
	0xce, 0x56, 0x11, 0x8b, 0x65, 0xee, 0xc6, 0x52, 0xe5, 0x52, 0xb5, 0x9f, 0x0b, 0x95, 0x5c, 0xb9,
	0xf5, 0x9f, 0xa1, 0xa2, 0x1e, 0x6a, 0x7a, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x20, 0x06, 0x8c,
	0x13, 0xd7, 0x02, 0x00, 0x00,
}

func (m *IndexerTendermintEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndexerTendermintEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndexerTendermintEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EventIndex != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.EventIndex))
		i--
		dAtA[i] = 0x28
	}
	if m.OrderingWithinBlock != nil {
		{
			size := m.OrderingWithinBlock.Size()
			i -= size
			if _, err := m.OrderingWithinBlock.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Subtype) > 0 {
		i -= len(m.Subtype)
		copy(dAtA[i:], m.Subtype)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Subtype)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IndexerTendermintEvent_TransactionIndex) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndexerTendermintEvent_TransactionIndex) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintEvent(dAtA, i, uint64(m.TransactionIndex))
	i--
	dAtA[i] = 0x18
	return len(dAtA) - i, nil
}
func (m *IndexerTendermintEvent_IsBlockEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndexerTendermintEvent_IsBlockEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintEvent(dAtA, i, uint64(m.IsBlockEvent))
	i--
	dAtA[i] = 0x20
	return len(dAtA) - i, nil
}
func (m *IndexerTendermintBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndexerTendermintBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndexerTendermintBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxHashes) > 0 {
		for iNdEx := len(m.TxHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TxHashes[iNdEx])
			copy(dAtA[i:], m.TxHashes[iNdEx])
			i = encodeVarintEvent(dAtA, i, uint64(len(m.TxHashes[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Events) > 0 {
		for iNdEx := len(m.Events) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Events[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Time, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintEvent(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if m.Height != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IndexerTendermintEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Subtype)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.OrderingWithinBlock != nil {
		n += m.OrderingWithinBlock.Size()
	}
	if m.EventIndex != 0 {
		n += 1 + sovEvent(uint64(m.EventIndex))
	}
	return n
}

func (m *IndexerTendermintEvent_TransactionIndex) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovEvent(uint64(m.TransactionIndex))
	return n
}
func (m *IndexerTendermintEvent_IsBlockEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovEvent(uint64(m.IsBlockEvent))
	return n
}
func (m *IndexerTendermintBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovEvent(uint64(m.Height))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Time)
	n += 1 + l + sovEvent(uint64(l))
	if len(m.Events) > 0 {
		for _, e := range m.Events {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if len(m.TxHashes) > 0 {
		for _, s := range m.TxHashes {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IndexerTendermintEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndexerTendermintEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndexerTendermintEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subtype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subtype = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionIndex", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OrderingWithinBlock = &IndexerTendermintEvent_TransactionIndex{v}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsBlockEvent", wireType)
			}
			var v IndexerTendermintEvent_BlockEvent
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= IndexerTendermintEvent_BlockEvent(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OrderingWithinBlock = &IndexerTendermintEvent_IsBlockEvent{v}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventIndex", wireType)
			}
			m.EventIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndexerTendermintBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndexerTendermintBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndexerTendermintBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Time, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Events", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Events = append(m.Events, &IndexerTendermintEvent{})
			if err := m.Events[len(m.Events)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHashes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHashes = append(m.TxHashes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
